# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsyslog < Formula
  desc ""
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jtarchie/jsyslog/releases/download/v0.0.1/jsyslog-darwin-0.0.1.tar.gz"
    sha256 "e20fa07c11bc91401d53c1e3781b6725fddc1c8046e662793bcf682e73eaf2b3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jtarchie/jsyslog/releases/download/v0.0.1/jsyslog-linux-0.0.1.tar.gz"
    sha256 "80814c7574c0fa9a6c4139762f71bee9ea903f2d1ec3d03fd107214e75638b5e"
  end

  def install
    bin.install "jsyslog"
  end

  test do
    system "#{bin}/jsyslog --version"
  end
end
